### ISSUE TITLE
Header size correcting

### ISSUE THREAD

**Issue by WillAMoore** [ojread/infinity-weddings#31]
had a look at correcting the header size, have been assuming that all of the items are on the menu.

Not sure what the best way of implementing this is, so I've just put this as an issue. 

Here is the css, with the bootstrap classes as headers
xs

leave as-is

small

.navbar-brand {
    font-size: 2em;
}

#menu-main-menu a {
    font-size: 0.7em;
    padding: 1.5em 0.5em 0.5em;
}

med
.navbar-brand {
    font-size: 2.5em;
}

a {
    font-size: 0.9em;
    padding: 1.3em 0.5em 0.5em;
}

large

.navbar-brand {
    font-size: 3em;
}

a {
    font-size: 1em;
    padding: 1em 0.5em;
}

**Comment by dylanpurple** [comment]
Hey Will, 

This should be fixed with the next pull request

Cheers
