### ISSUE TITLE
Navbar - Very Small Screens

### ISSUE THREAD

**Issue by dylanpurple** [ojread/infinity-weddings#47]
Hi Guys,

Any help you could give with this issue would be great - I have adjusted the navbar to work with the WP admin bar on all screens. However WP removes the static header bar on very small screens (600px or lower). This isn't using the standard Bootstrap break points. Any ideas on how to deal with this?

The work is on the navbar branch

Thanks

Less than 600

![home - 595x1053 595x649 - mozilla firefox_014](https://cloud.githubusercontent.com/assets/8179124/6105468/3e9c0a12-b04f-11e4-85d6-ddbc926b7ba8.png)

Just over 600

![home - 601x1053 601x649 - mozilla firefox_015](https://cloud.githubusercontent.com/assets/8179124/6105484/75c7f8ac-b04f-11e4-9cf4-470b120311ce.png)

**Comment by WillAMoore** [comment]
Maybe this function could help? http://codex.wordpress.org/Function_Reference/is_admin_bar_showing

**Comment by dylanpurple** [comment]
This only runs when PHP first executes - If you resize after that I think you may have the same problem but I could be wrong?

**Comment by WillAMoore** [comment]
No, I think you might be right

**Comment by dylanpurple** [comment]
Adding another media query outside of Bootstrap is probably not a good way to go either

**Comment by dylanpurple** [comment]
Using an additional media query fixed this
